services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8000:9000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      # Mailpit Configuration (Development)
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-noreply@example.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Laravel}
      # Redis Configuration (Development)
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      REDIS_DB: 0
      # Queue Configuration (Development)
      QUEUE_CONNECTION: redis
      # Broadcasting Configuration (Development)
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      # App Configuration (Development)
      APP_ENV: local
      APP_DEBUG: true
      LOG_LEVEL: debug
    volumes:
      - .:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/framework/cache:/var/www/html/storage/framework/cache
      - ./storage/framework/sessions:/var/www/html/storage/framework/sessions
      - ./storage/framework/views:/var/www/html/storage/framework/views
    depends_on:
      - db
      - redis
      - mailpit
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP server
    networks:
      - app-network

volumes:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge
